platform :ios, '9.3'
target 'ViroARkitsDavid' do
  use_frameworks!
  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'ViroKit', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/'
  pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
end
post_install do |installer|
  system(". ./pod_post_install.sh")
end